# The values in this file will be used if flags aren't given
# in CLI commands. Can create multiple --environments (default 'default')

[connections]
[connections.default]
input_parameters = "()"
return_type = "string"
name = "helloFunction"
handler = "app.hello"
file = "app.zip"

[connections.dev]
database = "<DATABASE_NAME>"
schema = "<SCHEMA_NAME>"
warehouse = "<WAREHOUSE_NAME>"
role = "<ROLE_NAME>"
