name: Integration testing

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

jobs:
  secret-check:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_HOST: ${{ secrets.SNOWFLAKE_HOST }}
    outputs:
      are-secrets-available: ${{ steps.check.results.are_secrets_available }}
    steps:
      - id: check
        shell: bash
        env:
          INTEGRATION_HOST: ${{ secrets.SNOWFLAKE_HOST }}
        run: |
          if [ "$INTEGRATION_HOST" == "" ]; then
            echo "are_secrets_available=false" >> "$GITHUB_OUTPUT"
          else
            echo "are_secrets_available=true" >> "$GITHUB_OUTPUT"
          fi

  test:
    runs-on: ${{ matrix.os }}
    needs: secret-check
    if: ${{ needs.secret-check.outputs.are_secrets_available == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip hatch
          python -m hatch env create integration
      - name: Run integration tests
        env:
          TERM: unknown
          SNOWFLAKE_CONNECTIONS_INTEGRATION_HOST: ${{ secrets.SNOWFLAKE_HOST }}
          SNOWFLAKE_CONNECTIONS_INTEGRATION_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_INTEGRATION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_INTEGRATION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: python -m hatch run integration:test
