name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        run: echo "Release created for ${{ github.event.release.tag_name }}"
