name: Testing

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

env:
  TERM: unknown  # Disables colors in rich


jobs:
  define-matrix:
    uses: ./.github/workflows/matrix.yaml
  tests:
    needs: define-matrix
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: |
          pip install -U hatch
          hatch env create default
      - name: Test with hatch
        run: hatch run test-cov
      - name: Run performance tests
        run: hatch run performance:test
      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
