name: "CLI Action testing"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  version:
    name: "Check Snowflake CLI version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: "tests_integration/config/connection_configs.toml"
      - name: Set workspace parent directory (Ubuntu / MacOS)
        run: echo "PARENT_DIR=$(dirname "${{ github.workspace }}")" >> $GITHUB_ENV
      - name: Run integration tests (Ubuntu / MacOS)
        env:
          TERM: unknown
          SNOWFLAKE_CONNECTIONS_INTEGRATION_AUTHENTICATOR: SNOWFLAKE_JWT
          SNOWFLAKE_CONNECTIONS_INTEGRATION_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_INTEGRATION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_INTEGRATION_PRIVATE_KEY_PATH: ${{ env.PARENT_DIR }}/.ssh/key.p8
          SNOWFLAKE_CONNECTIONS_INTEGRATION_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          mkdir ${{ env.PARENT_DIR }}/.ssh
          echo "${SNOWFLAKE_CONNECTIONS_INTEGRATION_PRIVATE_KEY}" > ${{ env.PARENT_DIR }}/.ssh/key.p8
          sudo chmod 600 ${{ env.PARENT_DIR }}/.ssh/key.p8
          python -m hatch run ${{ inputs.hatch-run }}
