name: Testing

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

env:
  TERM: unknown  # Disables colors in rich


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: |
          pip install -U hatch
          hatch env create default
      - name: Test with hatch
        run: hatch run test-cov
      - name: Run performance tests
        run: hatch run performance:test
      - uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8
